#!/bin/bash
#Launch an Android emulator and configure it for a local MyCHIPs server
#- Make sure there is a dns server accessible
#- Install locally generated CA file in the emulator
dnsLocIP="127.0.0.1"				#DNS from host's perspective
dnsEmuIP="10.0.2.2"				#DNS from emulator's perspective
cafile="../pki/local/web-ca.crt"		#Our local CA
pushpath="/sdcard/Download"

if [ -z "$1" ]; then
  avd="$(emulator -list-avds |sort -r |head -n 1)"	#default to highest level sdk
else
  avd="$1"
fi				#;echo "avd:$avd"; exit
logfile="../test/local/${avd}.log"
echo "Emulator logging to file: $logfile"

if ! nc -z $dnsLocIP 53; then
  echo "Error: Android emulator rquires a dns server on $dnsLocIP:53"
  exit 1
fi

devs="$(adb devices |grep -v attached |grep device)"
dev=$(echo $devs |head -n 1 |awk '{print $1}')
if [ ! -z "$dev" ]; then
  echo "Emulator is already running"
else
  echo "Launching emulator: $avd in writable mode"
  emulator -avd $avd -writable-system -no-snapshot-load -dns-server $dnsEmuIP -verbose >$logfile &
  adb wait-for-device				#Make sure emulator has launched
  dev="$(adb devices |grep -v attached |grep device }grep awk '{print $1}')"
fi

echo "Waiting for emulator boot, device:$dev"
adb wait-for-device shell 'while [[ -z $(getprop sys.boot_completed) ]]; do sleep 1; echo -n .; done;'
echo

capath=$pushpath/local_ca_file.crt
if ! adb -s $dev shell "[ -f $capath ]"; then
  echo "Installing local CA file on emulator at: $capath"
  sleep 5
  adb -s $dev push $cafile $capath
#  adb -s $dev shell am start -a android.intent.action.VIEW -d "file://$capath"
  adb -s $dev shell am start -n "com.android.settings/.Settings\$SecuritySettingsActivity"
  echo
  echo "On the running emulator, in settings, search for 'certificate'"
  echo " and install the CA certificate found in the download area"
else
  echo "Local CA file already on emulator: $capath"
fi
