#!/bin/env node
//Create a connection ticket for the admin account
//Usage ./adminticket <host> <port>
//TODO:
//- 

const Settings = require('../settings')
const { DBAdmin, MachineIP, AdminPort, AdminID } = Settings

var database = process.env.MYCHIPSDB || 'mychips'
var user = DBAdmin || process.env.MYCHIPSDBA || process.env.USER
var host = process.argv[2] || MachineIP
var port = process.argv[3] || AdminPort
//console.log("database:", database, "user:", user, "id:", AdminID)

var log = require('../../lib/logger')('AdminTicket')
var { dbClient } = require("wyseman")

var db = new dbClient({
  database, user, log,
  listen: "DummyChannel",
  schema: __dirname + "/../../lib/schema.sql"
})

let q = "select token, expires from base.token_login($1)"
db.query(q, [AdminID], (err, res) => {
    if (err) console.log("Error:", err.message, "\n  query:", q)
//console.log("res:", res)
    if (res && res.rows && res.rows.length >= 1) {
      let ticket = res.rows[0]
      ticket.host = host
      ticket.port = port
      console.log(JSON.stringify({ticket}))
    }
    db.disconnect()
})
