#!/usr/bin/env node
//A command-line client for testing/demonstrating how to connect to a MyCHIPs websocket
//Not for production use!
//Copyright MyCHIPs.org; See license in root of this package
// -----------------------------------------------------------------------------
// Usage examples:
//   entcli -a mychips0 -c ../pki/local/spa-ca.crt -t ../test/local/admin.json -u admin		//Connect with a one-time token (must specify the username)
//   entcli -c ../pki/local/spa-ca.crt						//Using an established key
//   entcli -v ../test/local/my-saved-key-file.json -s 'My secret passphrase'	//Using an encrypted key exported from another UI
// -----------------------------------------------------------------------------
// TODO:
//X- Save vault file encrypted
//X- Can decrypt vault file
//- 
const Yargs = require('yargs')			//Command line processing
const Readline = require('readline')		//Read/write command line
const Fs = require('fs')			//Filesystem
const Os = require('os')
const Homedir = Os.homedir()			//Where to store connection key
const Path = require('path')
const Wm = require('wyseman')			//Wyseman provides our client connection
const { Log } = require('wyclif')		//For logging
const dbInfo = ['mychips_user','wylib']		//Listen for these notifies from the DB

var log = Log('entcli')				//Instantiate a logger
var config = {dbInfo, log}			//Configuration options for connection

var argv = Yargs				//Process command line
  .alias('a', 'address')	.default('address',	'localhost')			//Hostname or IP address
  .alias('p', 'httpPort')	.default('httpPort',	8000)				//http port we will use briefly for authentication handshake
  .alias('w', 'wsPort')		.default('wsPort',	54320)				//Websocket port
  .alias('u', 'user')		.default('user',	process.env.USER)		//Username to connect as
  .alias('v', 'vault')		.default('vault',	Path.join(Homedir, '.mychips_keys'))	//Where to store my connection key
  .alias('s', 'secret')		.default('secret',	'my secret')			//A phrase to encrypt the private key
  .alias('c', 'caFile')				//Certificate Authority file
  .alias('t', 'ticket')				//One-time connection ticket
  .argv
log.debug("argv:", argv)
config.httpPort = argv.httpPort

let credential = {host:argv.address, port: argv.wsPort, user: argv.user}	//Will pass to connection builder
  , text2json = function(text) {		//Parse text to a JSON object
      let json = {}
      if (text) try {json = JSON.parse(text)} catch(e) {
        log.error("Parsing ticket JSON: ", text)
      }
      return json
    }

if (argv.ticket) {					//Connecting via a one-time ticket
  let tText = Fs.readFileSync(argv.ticket)		//Grab the ticket text
    , obj = text2json(tText)
  if (obj.ticket) {				//JSON does contain a ticket property
    let ticket = obj.ticket			//Some credential properties come from the ticket
    credential.token = ticket.token
    credential.host = ticket.host
    credential.port = ticket.port
    if (!credential.user) log.error("Must provide a username on the command line")
    
  } else {
    log.error("No ticket found in:", argv.ticket)
  }
log.debug("Ticket credentials:", credential)

} else if (Fs.existsSync(argv.vault)) {			//If we have a saved connection key
  let vaultText = Fs.readFileSync(argv.vault)
  credential = text2json(vaultText)
log.trace("Loaded credentials:", credential)

} else {	//User didn't specify -t or -v
  console.log("No connection token or key credentials found!")
  process.exit(1)
}

if (argv.caFile)
  config.ca = Fs.readFileSync(argv.caFile)		//Use a specified certificate authority file

var rl = Readline.createInterface({			//Initialize command line interface
  input: process.stdin,
  output: process.stdout,
  terminal: true
})
rl.setPrompt("> ")					//Set our prompt

let wmClient = new Wm.Client(config)			//Instantiate our connection to the backend

wmClient.on('password', () => {			//Call this when an encrypt/decrypt password is needed
  return argv.secret
})

wmClient.on('key', cred => {				//Call this when a key generated
log.debug("Writing connection key to vault:", argv.vault)
  Fs.writeFileSync(argv.vault, JSON.stringify(cred))	//Store my key for later use
})

wmClient.on('error', err => {				//Error handler
  log.debug("Websocket connection error:", err.message)
})

wmClient.connect(credential, ws => {			//Start a connection

  ws.on('message', msg => {				//We have an incoming message
log.debug("Websocket message:", msg)
    let obj; if (msg) try {obj = JSON.parse(msg)} catch(e) {	//Parse it to a JSON object
      log.error("Parsing JSON from db: ", msg)
    }
    console.log(JSON.stringify(obj,null,2))
    rl.prompt()
  })

  rl.on('line', line => {				//When the user inputs a line
    log.debug("Got user line:", line)
    handle(ws, line)					//Process it
  })

log.debug("Websocket open")
  rl.prompt()						//Give initial prompt
})

//Process command line input
//--------------------------------------------------------------------------------
const handle = function(ws, line) {

  let sendit = obj => {					//Send command object to the backend
    ws.send(JSON.stringify(obj))
  }

  let args = line.match(/\\?.|^$/g).reduce((p, c) => {		//Parse command line into arguments
    if(c === '"') {
      p.quote ^= 1;
    } else if(!p.quote && c === ' ') {
      p.a.push('');
    } else {
      p.a[p.a.length-1] += c.replace(/\\(.)/,"$1");
    }
    return  p;
  }, {a: ['']}).a
log.debug("Arguments:", args)
  let cmd = args.shift()				//First one is the command

  switch (cmd) {
    case 'list':
      sendit({
        id: 'list_cmd',					//Packet ID
        action: 'select',				//Our command
        view: 'mychips.users_v',
        fields: ['id', 'std_name', 'peer_endp']
      });						break;

    case 'pay':
      sendit({
        id: 'pay_cmd',
        action: 'select',
        view: 'mychips.users_v',
        table: 'mychips.users_pay',			//Example function--not yet implemented
        params: args					//Table will become a function with these arguments
      });						break;

    case 'exit':
      process.exit()

    default:
      if (cmd) console.log("Unknown command: " + cmd)
      rl.prompt()
  }
}
