#!/bin/bash
#Make one or more random users for use in agent modeling
#Copyright MyCHIPs.org; See license in root of this package
# -----------------------------------------------------------------------------
#TODO:
#- Update this to use node and to respect ../settings.js
#- Use agent, not servID
#- 

DBHOST=${MYCHIPS_DBHOST}; if [ -z "$DBHOST" ]; then DBHOST="localhost"; fi
DBNAME=${MYCHIPS_DBNAME}; if [ -z "$DBNAME" ]; then DBNAME="mychips"; fi

count=1
servID='null'
minDate="1940-01-01"
maxDate="2009-12-31"
minSecs=$(date -d "$minDate" +%s)
diffSecs=$(expr $(date -d "$maxDate" +%s) - $minSecs)
while [ $# -gt 0 ]; do
  if [ "x$1" = "x-n" ]; then		#-n <number> 	How many users to create
    count=$2
  elif [ "x$1" = "x-h" ]; then		#-h <servID>	Specify the server for the user(s)
    servID=$2
  fi
  shift 2
done
#echo "DBNAME:$DBNAME count:$count servID:$servID diffSecs:$diffSecs"

while [ $count -gt 0 ]; do
#  name="$(curl -s www.pseudorandom.name)"
  name="$(wget -O - www.pseudorandom.name 2>/dev/null)"
  read first last <<< "$name"
  cid="$(echo ${first}_${last} |tr '[:upper:]' '[:lower:]')"
  secs=$(expr ${RANDOM}${RANDOM} % $diffSecs + $minSecs)
  date=$(date -d "@$secs" +%Y-%b-%d)
  
  echo "first:$first last:$last cid:$cid date:$date"

#continue
  psql $DBNAME admin -h $DBHOST >/dev/null <<EOF
    insert into mychips.users_v (ent_name, fir_name, peer_cid, ent_type, born_date, serv_id)
    values('$last', '$first', '${cid}', 'p', '${date}', $([ "$servID" == 'null' ] && echo "null" || echo "'${servID}'"))
EOF
  count=$(expr $count - 1)
done
