#!/bin/sh

# An example hook script to verify what is about to be pushed.  Called by "git
# push" after it has checked the remote status, but before anything has been
# pushed.  If this script exits with a non-zero status nothing will be pushed.
#
# This hook is called with the following parameters:
#
# $1 -- Name of the remote to which the push is being done
# $2 -- URL to which the push is being done
#
# If pushing without using a named remote those arguments will be equal.
#
# Information about the commits which are being pushed is supplied as lines to
# the standard input in the form:
#
#   <local ref> <local oid> <remote ref> <remote oid>
#
# This sample shows how to prevent push of commits where the log message starts
# with "WIP" (work in progress).

TEST_DIR_NAME="__tests__"
remote="$1"
url="$2"

zero=$(git hash-object --stdin </dev/null | tr '[0-9a-f]' '0')
ROOT_DIR=$(git rev-parse --show-toplevel)

while read local_ref local_oid remote_ref remote_oid
do
	if test "$local_oid" = "$zero"
	then
		# Handle delete
		:
	else
		if test "$remote_oid" = "$zero"
		then
			# New branch, examine all commits
			range="$local_oid"
		else
			# Update to existing branch, examine new commits
			range="$remote_oid..$local_oid"
		fi

    changedFiles=$(git diff-tree --no-commit-id --name-only $range -r)
    echo "CHANGED FILES"
    echo $changedFiles
		# Check for WIP commit
    testDirs=()
    for file in $changedFiles
    do
      current=$file
      while [[ $current != "." ]]
      do
        current=$(dirname $current)
        if [ -d "${ROOT_DIR}/${current}/${TEST_DIR_NAME}/" ]
        then
          echo "PUSHING:" "${ROOT_DIR}/${current}/${TEST_DIR_NAME}/"
          testDirs+=("${ROOT_DIR}/${current}/${TEST_DIR_NAME}/")
          testDirs+=("${ROOT_DIR}/${current}/${TEST_DIR_NAME}/")
        fi
      done
      #Remove duplicates
    done
    echo "TEST DIRS:" $testDirs
    #remove duplicates
    testDirs=$(echo $testDirs | tr ' ' '\n' | sort -nu) 
    echo $testDirs
    exit 1
	fi
done

echo >&2 "NEVER PUSHING FOR DEBUG"
exit 2 #NEVER PUSH FOR TESTING
