#!/bin/bash
#Copyright MyCHIPs.org; See license in root of this package
# -----------------------------------------------------------------------------

for f in "$@"; do
  echo "Calculating hash for file: $f"
  oldhash="$(cat $f |grep digest: |sed -e 's/^ *digest: *//' -e s/\\\\x// |tr -d "'")"
  newhash="$(./hash $f)"
  echo "old:$oldhash"
  echo "new:$newhash"
  if [[ $newhash != $oldhash ]]; then
    if cat $f | sed -e "s/digest:.*$/digest: '\\\\x${newhash}'/" >$f.tmp; then
      cp $f $f.bak
      mv $f.tmp $f
    fi
  fi
done
