#!/usr/bin/env ruby
#Create server and client certificates for testing
# -----------------------------------------------------------------------------
require 'openssl'
require 'time'

server_key = OpenSSL::PKey::RSA.new(2048)
open('server_key.pem', 'w') do |io| io.write(server_key.to_pem) end
open('server_pub.pem', 'w') do |io| io.write(server_key.public_key.to_pem) end
client_key = OpenSSL::PKey::RSA.new(2048)
open('client_key.pem', 'w') do |io| io.write(client_key.to_pem) end
open('client_pub.pem', 'w') do |io| io.write(client_key.public_key.to_pem) end

name = OpenSSL::X509::Name.parse('CN=sslServer/DC=sslExample')
cert = OpenSSL::X509::Certificate.new
cert.version = 2
cert.serial = 0
cert.not_before = Time.now
cert.not_after = Time.now + (3600 * 24 * 7)
cert.public_key = server_key.public_key
cert.subject = name
cert.issuer = name
cert.sign(server_key, OpenSSL::Digest::SHA1.new)
open('server_cert.pem', 'w') do |io| io.write(cert.to_pem) end

name = OpenSSL::X509::Name.parse('CN=sslClient/DC=sslExample')
cert = OpenSSL::X509::Certificate.new
cert.version = 2
cert.serial = 0
cert.not_before = Time.now
cert.not_after = Time.now + (3600 * 24 * 7)
cert.public_key = client_key.public_key
cert.subject = name
cert.issuer = name
cert.sign(client_key, OpenSSL::Digest::SHA1.new)
open('client_cert.pem', 'w') do |io| io.write(cert.to_pem) end
