@startuml
!include common.puml
$title(Establishing/Using a Tally)
left to right direction

actor "User" as user
actor "Partner" as partner

usecase "Be My Vendor?" as offerStock
usecase "Be My Client?" as offerFoil
usecase "[[use-chit.png Transaction]]" as newChit
usecase "Request Close" as reqClose

user	--	offerStock
		offerStock	--	partner
user	--	offerFoil
		offerFoil	--	partner
user	--	newChit
		newChit		--	partner
user	--	reqClose
		reqClose	--	partner

@enduml
