@startuml
!include common.puml
$title(Route Query Response)
database "Downstream DB" as downDB
database "Local DB" as localDB
database "Upstream DB" as upDB

'collections "Other Peers on Network" as net

downDB	->>	localDB:	Receive route query

alt Route impossible via this path
  localDB	->>	downDB:	Reply action: fail

else Destination peer found locally
  localDB	->>	downDB:	Reply action: affirm

else Destination peer not found locally
  loop On upstream peers with lift capacity
    localDB	->>	upDB: Create draft route(s)\nQuery upstream
  end
end

  note over localDB: new route status indeterminate (pending)
  
alt Negative response
  upDB	->>	localDB:		Route impossible
  localDB	->>	localDB:	Set route status = fail
  localDB	->>	downDB:	Reply action: fail
  
else Positive response
  upDB	->>	localDB:		Route good
  localDB	->>	localDB:	Set route status = affirm
  localDB	->>	downDB:	Reply action: affirm

end
  note over localDB: routes will eventually time\nout and become stale

@enduml
