@startuml
!include common.puml
$title(Automatic Route Discovery)
control "Lift Agent" as agent
database "Local DB" as localDB
database "Upstream DB" as upDB
'database "Downstream DB" as downDB

agent	->	localDB:		Request scan of local segments

note over localDB
  Query for local segments that
  - have lift capacity; and
  - need route attention
end note

loop Over all segments with lift capacity
  alt Current routes available
    localDB	->>	localDB:	Initiate lift request on segment
  
  else Stale route found (good or failed)
    localDB	->>	upDB:		Request route refresh
    
  else No route found
    localDB	->>	upDB:		Request new route
    
  end
end

  note over localDB: route status initially indeterminate (pending)

alt Negative response
  upDB	->>	localDB:		Route impossible
  localDB	->>	localDB:	Set route status = bad
  
else Positive response
  upDB	->>	localDB:		Route good
  localDB	->>	localDB:	Set route status = good

end
  note over localDB: routes will eventually time\nout and become stale
  
@enduml
