@startuml
!include common.puml
$title(Establishing a Tally)
actor "Originator" as prop
database "Originator DB" as propDB
database "Subject DB" as subjDB
actor "Subject" as subj

prop	->>	propDB:		Create draft, signed tally/ticket
note over propDB
  Ticket may be permanent or expiring and for one or multiple peers
end note
prop	-[#red]>> subj:		Communicate ticket to peer via QR code (out-of-band)
subj	->>	subjDB:		Add peer specified in ticket
subjDB	->>	propDB:		Connect via ticket, exchange keys
propDB	->	propDB:		Detect pending proposed tally
propDB	->>	subjDB:		Send proposed tally
subjDB	->>	subj:		Present for review
loop until satisfied
 subj	->>	subjDB:		Modify tally terms
end loop

alt Terms agreeable
 subj	->>	subjDB:		Accept/sign tally
 subjDB ->>	propDB:		Send accepted tally
 propDB	->>	prop:		Store and notify user

else Want to counter
 subj	->>	subjDB:		Counter offer
 subjDB	->>	propDB:		Send proposed tally
 propDB	->>	prop:		Present for review
 prop	->>	propDB:		Accept/sign tally
 propDB	->>	subjDB:		Send accepted tally
 subjDB	->>	subj:		Store and notify user

else Refuse terms
 subj	->>	subjDB:		Mark tally as refused
 subjDB ->>	propDB:		Send accepted tally
 propDB	->>	prop:		Store and notify user
end

note over propDB, subjDB
  Signed tally can now be used for transactions
end note

@enduml
