@startuml
!include common.puml
$title(Chit Chain Consensus Protocol)
actor "Stock Holder" as vendor
database "Stock DB" as stock
database "Foil DB" as foil
actor "Foil Holder" as client

alt Foil validates chit
  client	->>	foil:		Apply validating signature to chit
  foil		->>	stock:		Transmit new valid Chit\nwith validating signature\nAnd new endHash

  alt Stock agrees with new endHash
    stock	->>	stock:		Ratchet forward\nackHash = endHash
  else Stock disagrees, has different end of chain
    stock	->>	stock:		Conform to Foil chain\nRequeue/send bumped and/or\nunchained chits as new
  end
  
else Stock validates chit
  vendor	->>	stock:		Apply validating signature to chit
  stock		->>	foil:		Transmit new valid Chit\nwith validating signature\nAnd proposed endHash: propHash
  foil		->>	foil:		Add/link new valid chit\nat end of chain

  alt Foil agrees with stock's proposed endHash
    foil	->>	foil:		Ratchet forward\nackHash = propHash
    foil	->>	stock:		Acknowledge propHash was correct
    stock	->>	stock:		Ratchet forward\nackHash = propHash

  else Foil disagrees with stock's proposed endHash
    foil	->>	stock:		Send chits since last ackHash\nand correct endHash

    alt Can chain/reconcile received chits and confirm endHash
      stock	->>	stock:		Conform to Foil chain\nRequeue/send bumped and/or\nunchained chits as new
    else Can't chain/reconcile received chits
      stock	->>	vendor:		Report error to user
      stock	->>	foil:		Report error
      foil	->>	client:		Report error to user
    end
  end

end
    
@enduml
