@startuml
!include common.puml
$title(Chit Direct Invoice)
actor "Payor" as pay
database "Payor DB" as payDB
database "Receiver DB" as recDB
actor "Receiver" as rec

rec	->>	recDB:		Submit draft chit w/\nvalue --> receiver
recDB	->>	payDB:		Store, transmit to peer
payDB	->>	pay:		Notify user

alt Terms agreeable
 pay	->>	payDB:		Accept/sign chit
 note over payDB, recDB
   Payment is now binding
 end note
 payDB	->>	recDB:		Store and transmit to peer
 recDB	->>	rec:		Store and notify user

loop until consensed
 payDB	<->	recDB:		Consensus acks/naks
end loop

else Want to counter
 loop until satisfied
  pay	->>	payDB:		Modify invoice terms
 end loop
 pay	->>	payDB:		Return counteroffer
 payDB	->>	recDB:		Send modified draft chit
 recDB	->>	rec:		Store and notify user
 note over recDB, rec
   Invoice chit may then be modified/resubmitted (above)
 end note

else Refuse terms
 pay	->>	payDB:		Mark chit as refused
 payDB	->>	recDB:		Send refused chit
 recDB	->>	rec:		Store and notify user
end

@enduml
