@startuml
!include common.puml
$title(Lift Relay and Terminus Response)
actor "User" as user
control "Downstream Agent" as dnAgent
control "Local Agent" as relAgent
database "Local Model" as relDB
control "ChipNet" as chipNet
collections "Upstream Sites" as upSites

dnAgent		->>	relAgent:	Routing query from below
relAgent	->>	chipNet:	Packet handled by ChipNet
chipNet		<->	relDB:		Query local DB for:\nedge/segment candidates
chipNet		<->	upSites:	ChipNet negotiates pathway
chipNet		->>	dnAgent:	Propagate query response

note over relAgent, chipNet:		Respond with sequence above as needed\nto resolve routing

dnAgent		->>	relAgent:	Receive transaction\nrecord update
relAgent	->>	chipNet:	Hand off packet to ChipNet

chipNet		<->	relDB:		Fetch transaction state, if any

alt Next step: promise
  chipNet	->>	relAgent:	Should we proceed to promise?
  relAgent	<->	relDB:		Lift still OK to proceed?
  
  alt Yes, promising
    relAgent	->>	relDB:		Build lift record and draft chits
    relAgent	->>	chipNet:	Respond affirmatively
  else
    relAgent	->>	chipNet:	Respond negatively
  end

else Next step: commit
  chipNet	->>	relAgent:	Time to commit
  relAgent	->>	relDB:		Commit provisional chits

else Next step: abort/rollback
  chipNet	->>	relAgent:	Abort lift
  relAgent	->>	relDB:		Void provisional chits

end

chipNet	->>	upSites:	Propagate update records
relAgent	->>	user:		Notify user

@enduml
