@startuml
!include common.puml
$title(Route Query Response (WIP))
control "Lift Agent" as agent
database "Local DB" as localDB
database "Upstream DB" as upDB
database "Downstream DB" as downDB

'collections "Other Peers on Network" as net

localDB	->>	upDB:		Something here

note over localDB
  Note here
end note

'alt User specified this partner explicitly
'  userDB	->	partDB:		Request route refresh
'  
'else This tally lacks capacity
'  userDB	->	userDB:
'  note right: Do nothing
'
'else No existing route found
'  userDB	->	partDB:		Query for new route
'
'else Existing stale route found
'  userDB	->	partDB:		Request route refresh
'
'else Existing route is (recently) failed
'  userDB	->	userDB:
'  note right: do nothing
'end

@enduml
