@startuml
!include common.puml
$title(Establishing a Tally)
actor "Originator" as prop
database "Originator DB" as propDB
database "Subject DB" as subjDB
actor "Subject" as subj

prop	->>	propDB:		Create draft tally & ticket
note over propDB
  Ticket may be one-time or reusable for multiple peers
end note
prop	-[#red]>> subj:		Communicate ticket to subject peer via QR code (out-of-band)
subj	->>	subj:		Select Certificate\ninfo to disclose
subj	->>	subjDB:		Request to connect via ticket
subjDB	->>	propDB:		Is this a known or local agent?\nConnect w/ticket or known key,\nattach subject certificate
propDB	->	propDB:		Construct/complete draft tally
propDB	->>	prop:		Present for review
prop	->>	propDB:		Sign/Offer tally
propDB	->>	subjDB:		Send proposed, signed tally
subjDB	->	subjDB:		Store tally locally,\ncheck for local partner
subjDB	->>	subj:		Present tally for review
loop until satisfied
 subj	->>	subjDB:		Modify tally terms\n(invalidates partner signature)
end loop

alt Terms agreeable
 subj	->>	subjDB:		Accept/sign tally\n(if no changes made)
 subjDB ->>	propDB:		Send accepted tally
 propDB	->>	prop:		Store and notify user
 propDB -[#violet]>>	propDB:		Initiate consensus ack sequence
 propDB -[#violet]>>	subjDB:		(Transmit consensus ack/nack)

else Want to counter
 subj	->>	subjDB:		Sign modified counter-offer
 subjDB	->>	propDB:		Update revision count\nsend proposed tally
 propDB	->>	prop:		Present for review
 prop	->>	propDB:		Accept/sign tally
 propDB	->>	subjDB:		Send accepted tally
 subjDB	->>	subj:		Notify user
 subjDB -[#violet]>>	subjDB:		Initiate consensus ack sequence
 subjDB -[#violet]>>	propDB:		(Transmit consensus ack/nack)

else Refuse terms
 subj	->>	subjDB:		Request to void tally
 subjDB ->>	propDB:		Send refusal message
 propDB	->>	prop:		Store and notify user
end

note over propDB, subjDB
  Signed tally can now be used for transactions
end note

@enduml
