@startuml
!include common.puml

$title(Chit State Diagram)
[*] --> void
state "void (or No Chit)" as void

'States are determined by a combination of values, as defined here:
userRequest: Stat: void, Req=>userRequest
userRequest : E: Store chit
peerInvoice: Stat: void, Req=null
peerInvoice : E: Store chit
userInvoice: Stat->pend, Req=null
peerDecline : Stat:->void, Req=null
peerInvoice : E: Update chit

'State transition rules:
void -left[$peer]-> peerInvoice : $trans($peer,Requests payment,'',Notify user)
void -right[$user]-> userRequest : $trans($user,Creates chit Record)

userRequest -[$db]-> userInvoice : $trans($db,Req:userRequest detected,'',Transmit chit Act:peerInvoice)
userInvoice --> userRequest : $trans(Timeout,No reply from peer)
userInvoice -[$peer]-> peerDecline : $trans($peer,Declines,'',Notify user)
peerDecline -[$user]-> userRequest : $trans($user,Modifies chit,'')
userInvoice -[$peer]-> peerDecline : $trans($peer,Declines,'',Notify user)

'Fixme: Need to add more states here

'closed --> [*]

@enduml
