@startuml
!include common.puml

$title(Tally State Diagram)

state Syncing {
    state TheirCourt {
        state Waiting
        state Abandoned
    }
    state YourCourt {
        state Voided
        state Reviewing
        state Drafting
    }
    state SendingOffer
    state SendingApproval
}
state Tradable {
    state Open
    state ClosePending
}
state Closed

[*] -right-> Drafting: NewTally
[*] --> Reviewing: OfferReceived

YourCourt --> Voided: Void
Drafting --> SendingOffer: Approved

SendingOffer --> Waiting: OfferSent

Reviewing --> SendingApproval: Approve
Reviewing --> Drafting: Reject

TheirCourt --> Reviewing: OfferReceived
TheirCourt --> Open: AgreeReceived

Waiting --> Abandoned: AbandonReceived

SendingApproval --> Open: ApprovalReceived

Open --> ClosePending: Close

ClosePending --> Closed: Closed

' Syncing --> Waiting: OutOfSyncWait
' Syncing --> Reviewing: OutOfSyncReview
' Syncing --> Voided: OutOfSyncVoided
' Syncing --> Abandoned: OutOfSyncVoided
Syncing --> Syncing: OutOfSync

@enduml
