@startuml
!include common.puml

$title(Chit Chain Consensus Stock States)
[*] --> cons
cons: Fully Consensed
error: Can't Consense
pend: Pending Acknowledge
problem: Does not reconcile
request: Requested Update
newChit: Regular chit processing

'state stock {
'  stockPend:
'  stockRequest:
'}

'State transition rules:
cons -[$user]-> newChit: $trans($user, User creates new\nvalid direct chit(s),'')
cons -[$db]-> newChit: $trans($db, Site creates new\nvalid lift chit(s),'')

newChit -[$db]-> pend: $trans($db,Detected new valid chit(s),'', 'Add to chain provisionally\nGenerate proposed endHash: propHash\nSend to Foil peer Act:prop')

cons -[$peer]-> cons: $trans($peer,Receive new chit Act:new,'Can reconcile endHash', 'Conform to chain\nackHash = newHash')
cons -[$peer]-> problem: $trans($peer,Receive new chit Act:new,'Cannot reconcile endHash')
problem -[$db]-> request: $trans($db,Detected failed state,'', 'Request update from Foil\nAct:compare')

request -[$peer]-> error: $trans($peer,Receive chits since ackHash Act:update,'Cannot reconcile with endHash', 'Send error report to peer and user')
request -[$peer]-> cons: $trans($peer,Receive chits since ackHash Act:update,'Chain now reconciles with endHash', 'ackHash = endHash')
request -[$peer]-> newChit: $trans($peer,Receive chits since ackHash Act:update,'Still have unlinked chit(s)', 'Requeue for sending')

pend -[$peer]-> cons: $trans($peer,Receive ack from Foil Act:ack,'Agree with proposed endHash', 'Ratchet: ackHash = propHash')

@enduml
