@startdot
digraph lifts {
  label = "Lift Test Graph";

  subgraph cluster_agent0 {
    label = "Agent 0"
    userU [label="User U\np1001"];
    userB [label="User B\np1003"];
    userX [label="User X\np1002"];
    userA [label="User A\n(not present)" style=dotted];
  }

  subgraph cluster_agent1 {
    label = "Agent 1"
    user0 [label="User 0\np1000"];
    user1 [label="User 1\np1001"];
    user2 [label="User 2\np1002"];
    user3 [label="User 3\np1003"];
  }

  subgraph cluster_agent2 {
    label = "Agent 2"
    userD [label="User D\np1000"];
  }

   userU -> user0 [label="B8 L8"];
   user0 -> user1 [label="B2 L7 D1"];
   user1 -> user2 [label="B4 L9"];
   user2 -> user3 [label="B6 L11"];
   user3 -> userD [label="B10 L15"];

   user2 -> user0 [label="B14 L19"];
   user1 -> user3 [label="B-12 D15"];

   user0 -> userA;
   userB -> user2 [label="B0 L5"];
   userX -> userB [label="B0 L5"];
   userD -> userX [label="B0 L5"];
}
@enddot
