@startuml
!include common.puml
$title(Lift Use Cases)
left to right direction

node "Originator" as originator
node "Referee" as referee
node "Relay Nodes" as relayNodes
node "Destination" as destNode

usecase "#1\nPropose a lift using a named referee" as proposed
usecase "#2\nConfirm lift circuit completion" as confirm
usecase "#3\nAsk the referee to ratify a lift" as ratify
usecase "#4\nTransmit commit information" as commit
usecase "#5\nQuery the referee" as query

originator	--	proposed
			proposed	-- relayNodes
			proposed	-- destNode

originator	--	confirm
			confirm		-- destNode

originator	--	ratify
referee		--	ratify

originator	--	commit
			commit		-- relayNodes
			commit		-- destNode

referee		--	query
			query		-- relayNodes
			query		-- destNode

@enduml
