@startuml
!include common.puml
$title(Lift Confirmation/Ratification)
participant "Referee" as referee
database "Originator DB" as propDB
collections "Intermediate nodes" as inter
database "Terminus DB" as termDB

propDB		->>	inter:		Will you participate in this lift?
inter		->>	termDB:		Will you participate in this lift?

note over termDB: The destination is a local user
termDB		->>	propDB:		Terminus reached;\nauthenticate

alt Originator wants to cancel the lift
  propDB	->>	propDB:		Wait until lift has expired
  propDB	->>	referee:	Has lift expired?\nGet void signature
end

propDB	->>	referee:	Request to commit this lift\nGet good/void signature

referee	->>	propDB:		Here's my signature\n(whether good or void)

note over propDB
  Lift is now irrevocably good and binding
  or void and safely ignorable.  A good
  signature is a liability to any node
  who doesn't deploy it (because their 
   upstream neighbor probably will).
end note
    
propDB	->>	termDB:		Here's the signature; consense
termDB	->>	inter:		Here's the signature; consense
inter	->>	propDB:		Here's the signature; consense

@enduml
