#!/bin/bash
#Initialize an empty database with some sample data
MYPATH=$(dirname "$0")

psql $USER -c "select base.parmset('mychips','mobi_inet','192.168.58.101'::inet)"
psql $USER -c "update mychips.users set mobi_inet = '192.168.58.101' where not mobi_inet isnull;"

echo "CWD:$(pwd) MYPATH:$MYPATH"
mc_admin load -s $MYPATH/org.json
mc_admin load $MYPATH/user.json
mc_admin ticket 10000 $MYPATH/../tmp/ticket.json

