#!/bin/bash
#Show all tallies belonging to a certain user
#or show both halves of all tallies owned by partner1 and shared with partner2

if [ -z "$1" ]; then
  echo 'Usage: tally_show partner1 <partner2>'
  exit 1
fi
p1="$1"
p2="$2"

if [ -z "$p2" ]; then
  sub="select distinct tally_uuid from mychips.tallies where tally_ent = '$p1'"
else
  sub="select distinct tally_uuid from mychips.tallies where tally_ent = '$p1' and part_ent = '$p2'"
fi

#echo "$sub"
echo "select tally_ent,tally_seq,tally_type,part_ent,tally_uuid,net_pc,state from mychips.tallies_v where tally_uuid in ($sub) order by 1,2;"
