#!/bin/bash
#Conditionally rebuild/update the database schema if any files look fresher than
#the last time this script was run.
#Usage:	./builddb
newusers=5

#Common code
#-------------------------------------------------------------------------------
thisscript="${BASH_SOURCE}"
this="$(basename ${BASH_SOURCE})"
mypath="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )";	#echo "mypath:$mypath"
source $mypath/config
lastfile=${tmpdir}/last_schema_build

if ! cd "${mypath}/../.." || [ "$(basename "$(pwd)")" != 'mychips' ]; then
  echo "Can't find MyCHIPs source directory"
  exit 1
fi

if ! cd schema; then
  echo "Can't find schema directory"
  exit 1
fi

dobuild=false
if [ ! -f $lastfile ]; then
  dobuild=true
else
  news=$(find . -newer $lastfile |wc -l)
  if [ $news -gt 0 ]; then
    dobuild=true
  fi
fi

#echo "dobuild:$dobuild"

#No DB yet: let's build everything
if [ "$(psql -A -t template1 admin -c "select * from pg_database where datname = 'mychips'" |wc -l)" -lt 1 ]; then
  make objects text defs init
  dobuild=false
  date >$lastfile
fi

if $dobuild; then
  make objects parm
  date >$lastfile
fi

if [ "$(psql -A -t mychips admin -c "select * from mychips.users_v where ent_num > 1" |wc -l)" -lt $newusers ]; then
  ../test/sample/randuser -n $newusers
fi
