#!/bin/bash
#Run a command on all the machines part of our simulation
#Usage:	./netcmd uptime
#
#TODO:
#- 

#-------------------------------------------------------------------------------
this="$(basename ${BASH_SOURCE})"
mypath="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )";	#echo "mypath:$mypath"
source $mypath/config
hostlist=''

for mach in "${locals[@]}"; do
  echo -- "----->" $mach $*
  if [ -z "$hostlist" ]; then
    hostlist="$mach"
  else
    hostlist="${hostlist},$mach"
  fi
done

for mach in "${remotes[@]}"; do
  echo -- "----->" $mach $*
  if [ -z "$hostlist" ]; then
    hostlist="$mach"
  else
    hostlist="${hostlist},$mach"
  fi
done

#for i in "$@"; do
#  echo "$i"
#done
pdsh -w $hostlist -R ssh "$@"
