#!/bin/bash
#Run an sql query on all the machines part of our simulation
#Usage:	./netcmd uptime
#
#TODO:
#- 

#-------------------------------------------------------------------------------
this="$(basename ${BASH_SOURCE})"
mypath="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )";	#echo "mypath:$mypath"
source $mypath/config

./netcmd psql $dbname $admin -c \'"$@"\'
