#!/bin/bash
#Run pre-defined reports on selected remote sites
#Copyright MyCHIPs.org; See license in root of this package
# -----------------------------------------------------------------------------
#TODO:
#- 

report="$1"; shift
nodes="$1"; shift
if [ -z "$nodes" ]; then
  nodes="0"
fi
  
case $report in
    tallies)
      query="select tally_ent ent,tally_seq seq,tally_type typ,hold_cid,hold_agent,part_cid,part_agent,net,target tgt, status, tally_uuid from mychips.tallies_v";;

    chits)
      query="select chit_ent ent,chit_seq seq,chit_idx idx,chit_type typ,chit_uuid,units,status,state from mychips.chits_v";;

    edges)
      query="select tally_ent,tally_seq,tally_type,type,inp,out,min,max,uuid,canlift from mychips.tallies_v_net";;

    paths)		#Local paths
      query="select out_cid,top_cid,bot_cid,inp_cid,edges,min,max,bang,circuit,path from mychips.tallies_v_paths where segment";;

    routes)
      query="select rid,status,min,max,dst_cid,dst_agent,via_cid,vip_cid,req_cid,step,status from mychips.routes_v where status = 'good'";;

    xpaths)		#External pathways
      query="select out_cid,top_cid,bot_cid,inp_cid,min,max,status,circuit from mychips.routes_v_paths where status = 'good'";;

    xlifts)		#External lifts (circuit pathways)
      query="select out_cid,top_cid,bot_cid,inp_cid,min,max,status,circuit from mychips.routes_v_paths where status = 'good' and circuit";;

    lifts)
      query="select lift_uuid,lift_seq,request,status,units,circuit,find,signature from mychips.lifts_v";;

    *)
      echo "Unknown report: $report"
      exit 1
      ;;
esac

echo "./simdock q $nodes \"$query\" $@"
./simdock q "$nodes" "$query $@"
