#!/bin/bash
#Run pre-defined reports on selected remote sites
#Copyright MyCHIPs.org; See license in root of this package
# -----------------------------------------------------------------------------
#TODO:
#- 

report="$1"; shift
nodes="$1"; shift
if [ -z "$nodes" ]; then
  nodes="0"
fi
  
case $report in
    xlifts)		#External lifts
      query="select first,path,status,lift_margin,lift_reward,lift_min,lift_max from mychips.routes_v_lifts order by 3";;

    xpaths)		#External pathways
      query="select first,last,length,path,lift_min,lift_margin,lift_max,lift_reward,status,dest_chid from mychips.routes_v_paths where status = 'good'";;

    paths)		#Local paths
      query="select first,last,length,path,lift_min,lift_max,bang,lift_margin,lift_reward from mychips.tallies_v_paths where corein and fora and forz";;

    routes)
      query="select route_ent,route_addr,dest_chad,status,step,lift_min,lift_margin,lift_max,lift_reward from mychips.routes_v where status = 'good'";;

    chits)
      query="select chit_ent,chit_seq,chit_idx,chit_type,chit_guid,units,status,state from mychips.chits_v";;

    tallies)
      query="select tally_ent,tally_seq,partner,tally_type,units,units_gc,units_pc,target,bound,reward,clutch from mychips.tallies_v";;

    lifts)
      query="select lift_guid,lift_seq,request,status,units,circular,path,dest_chid,dest_host,signature from mychips.lifts_v";;

    *)
      echo "Unknown report: $report"
      exit 1
      ;;
esac

echo "./simdock q $nodes \"$query\" $@"
./simdock q "$nodes" "$query" "$@"
