#!/bin/bash
#Set path to include local npm develment modules
#Usage:	. setpath

#Common code
#-------------------------------------------------------------------------------
this="$(basename ${BASH_SOURCE})"
mypath="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"	#;echo "mypath:$mypath"
mcpath="$( cd "$mypath/../.." && pwd )"				#;echo "mcpath:$mcpath"
dvpath="$( cd "$mcpath/.." && pwd )"				#;echo "dvpath:$dvpath"

if [ "$(basename "$mcpath")" != 'mychips' ]; then
  echo "Can't find MyCHIPs source directory"
else
  export PATH=${PATH}:${dvpath}/node_modules/.bin
fi
