#!/bin/bash
#Copyright MyCHIPs.org; See license in root of this package
# -----------------------------------------------------------------------------
mypath="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )";	#echo "mypath:$mypath"
source $mypath/config.dock

mychips="$mypath"					#Get our bearings in the filesystem
mysim=""
while [[ $path != / ]]; do				#Find first bin dir above me
  if find "$mychips" -maxdepth 1 -mindepth 1 -type d -name bin | grep -q .; then
    break
  fi
  mysim="$(basename $mychips)/${mysim}"			#Find simulation directory
  mychips="$(cd $mychips/.. && pwd)"
done

# Export needed variables (docker-compose.yml can only access env vars)
export mypath=$mypath
export mysim=$mysim
export mychips=$mychips
export locdir=$locdir
export sites=1          # Some adjustments will need to be made to the docker structure to get this to be more than 1
export NODE_DEBUG=debug
export mongorepset=$mongorepset
export version=$version

command="$1"

if [ 'start' = $command ]; then
    docker compose up -d
elif [ "stop" = $command ]; then
    docker compose down
elif [ "map" = $command ]; then
    docker compose convert
# elif [ "publish" = $command ]; then     # builds in AWS
    # docker compose --context=ecscontext up
else
    echo "Sorry, I don't recognize that command!"
fi
