#!/bin/bash
#Copyright MyCHIPs.org; See license in root of this package
# -----------------------------------------------------------------------------
#Run multiple servers on a single machine to simulate a small MyCHIPs network
#Linux/x11 only
#TODO:
#- Change obsolete --servID to use new --agent form of server identity
#- 
size="80x24"						#X-window size
gx=20; gy=320; offx=500; offy=0;			#Window geometry placement offsets

#path="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/..";	#echo "path:$path"
path=$(pwd)
while [[ $path != / ]]; do				#Find first bin dir above me
  if find "$path" -maxdepth 1 -mindepth 1 -type d -name bin | grep -q .; then
    break
  fi
  path="$(readlink -f "$path"/..)"
done

basecmd="NODE_DEBUG=debug $path/bin/mychips.js --no-spaPort --no-adminPort --no-userPort --no-clifPort --docs 0"
baseport=65430						#Peer port for first server
nextServer=0						#Keep track of how many servers launched
serversPIDs=()						#And remember their PIDs
#echo "path:$path basecmd:$basecmd baseport:$baseport"; exit 0;

#Start up a server, in a window, at port=$1
function launchServer {
  idx=$nextServer
  port=$(expr $baseport + $idx)
  rcfname="mychips-$idx-$port.rc"
  cmd="$basecmd --peerPort=$port --servID=server$idx"
echo "idx:$idx port:$port rcfname:$rcfname cmd:$cmd"
  echo $cmd >/tmp/$rcfname
  geom="+$(expr $offx \* $idx + $gx)+$(expr $offy \* $idx + $gy)"
  xterm -geometry $size$geom -e "bash --init-file /tmp/$rcfname" &
  pid=$!
echo "Launched server $idx at port:$port, $geom"
  serverPIDs+=($pid)
  nextServer=$(expr $nextServer + 1);		#echo "PIDs:${serverPIDs[@]}"
}

function cleanup {				#Do on exit
  echo -n "Killing servers: "
  port="$baseport"
  for pid in ${serverPIDs[@]}; do
    kill $pid;	    echo -n "$pid "		#Kill the xterm
    read spid junk <<<"$(ps x |grep node.*$port |grep -v grep)"
    kill $spid;    echo -n "$spid "		#Kill the server
    port=$(expr $port + 1)
  done
  echo
}
trap cleanup EXIT

if [ -z "$1" ]; then count=2; else count="$1"; fi	#Default: 2 servers, or specify more
while [ $count -gt 0 ]; do
  launchServer
  count=$(expr $count - 1)
done

echo "Type 'x' to kill and exit"
while true; do					#Menu for other functions?
  echo -n "> "
  read ans
  if  [ "$ans" = "x" ]; then
      exit
  fi
done
